services:

  # Frontend - React + Vite (Static Site)
  - type: web
    name: expense-tracker-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "https://trackerexpense-2.onrender.com"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
